# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Executing'), (2, 'Successfully'), (3, 'Failed')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.ProjectBranche')),
            ],
        ),
        migrations.CreateModel(
            name='ExportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_path', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.ProjectBranche')),
            ],
        ),
    ]
