# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0002_exporthistory_exportsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Executing'), (2, 'Successfully'), (3, 'Failed')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.ProjectBranche')),
            ],
        ),
    ]
