# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0003_synchistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='project',
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocal.Module'),
        ),
        migrations.AlterField(
            model_name='protocal',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocal.Message', unique=True),
        ),
        migrations.AlterField(
            model_name='protocallabel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
