# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocal', '0004_auto_20181021_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocal',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocal.Message'),
        ),
    ]
